DROP TABLE USER_CREDENTIALS;
CREATE TABLE user_credentials (
    user_name           VARCHAR(50),
    mobile_number       VARCHAR(15),
    active_status       CHAR(1) DEFAULT 'Y',
    password            VARCHAR(20) NOT NULL,
    created_datetime    TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    modified_datetime   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT pl PRIMARY KEY ( user_name,
                                mobile_number )
);

DROP SEQUENCE SEQ_USER_PROFILE;
CREATE SEQUENCE SEQ_USER_PROFILE MINVALUE 100000 MAXVALUE 999999 START WITH 100000 INCREMENT BY 1 CACHE 100;

DROP TABLE USER_PROFILE;
CREATE TABLE user_profile (
    SEQ_USER_PROFILE    VARCHAR(10) PRIMARY KEY, 
    user_name           VARCHAR(50) NOT NULL,
    mobile_number       VARCHAR(15) NOT NULL,
    active_status       CHAR(1) DEFAULT 'Y',
    display_name        VARCHAR(150) NOT NULL,
    first_name          VARCHAR(15) NOT NULL,
    last_name           VARCHAR(20) NOT NULL,
    email_id            VARCHAR(45) NOT NULL,
    age                 INTEGER DEFAULT NULL,
    height              INTEGER DEFAULT NULL,
    weight              INTEGER DEFAULT NULL,
    address             VARCHAR(255) NOT NULL,
    city                VARCHAR(50) NOT NULL,
    state               VARCHAR(60) NOT NULL,
    date_of_birth       DATE NOT NULL,
    pin_code            VARCHAR(6) NOT NULL,
    created_datetime    TIMESTAMP(6) DEFAULT systimestamp(6),
    modified_datetime   TIMESTAMP(6) DEFAULT systimestamp(6),
    FOREIGN KEY ( user_name,
                  mobile_number )
        REFERENCES USER_CREDENTIALS ( user_name,
                                          mobile_number ) ON DELETE CASCADE
    
    );


DROP TABLE DL_LICENSE_CLASSES;
CREATE TABLE dl_license_classes (
    v_class         VARCHAR(30) NOT NULL,
    v_class_desc    VARCHAR(100) NOT NULL,
    active_status   CHAR(1) DEFAULT 'Y'
);

TRUNCATE TABLE dl_license_classes;
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('MC 50CC','Motorcycles with an engine capacity of 50 cc or less');
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('MC EX50CC','Motorcycles and (Light Motor Vehicle)CAR with engine capacity of more than 50 cc');
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('FVG','Motorcycles of any engine capacity, but without gears, including mopeds and scooters');
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('M/CYCL.WOG','Motorcycle Without Gear  all motorcycles, Scooters');
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('M/CYCL.WG','Motorcycle With Gear all motorcycles');
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('LMV','Light Motor Vehicle including motorcars, jeeps, taxis, delivery vans');
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('LMV-NT','Light Motor Vehicle Non Transport for personal use only');
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('LMV-TR','Light Motor Vehicle Transport for commercial transportation including light goods carrier');
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('HMV','Heavy Motor Vehicle');
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('HPMV','Heavy Passenger Motor Vehicle');
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('HTV','Heavy Transport Vehicle (Heavy Goods and Heavy Passenger Motor Vehicle)');
INSERT INTO dl_license_classes (v_class,v_class_desc) VALUES ('TRAILER','A person holding a heavy vehicle driving licence can only apply for heavy trailer licence');


DROP TABLE VEHICLE_DETAILS;
CREATE TABLE vehicle_details (
    v_registration_num   VARCHAR(10) PRIMARY KEY,
    v_user_name          VARCHAR(45) NOT NULL,
    v_mob                VARCHAR(15) NOT NULL,
    active_status        CHAR(1) DEFAULT 'Y',
    FOREIGN KEY ( v_user_name,
                  v_mob )
        REFERENCES user_credentials ( user_name,
                                  mobile_number )
            ON DELETE CASCADE
);


DROP TABLE PERSONAL_IDENTITY_TYPE;
CREATE TABLE personal_identity_type (
    pi_type            VARCHAR(15) NOT NULL,
    pi_category_type   VARCHAR(12) NOT NULL,
    active_status      CHAR(1) DEFAULT 'Y'
);

TRUNCATE TABLE personal_identity_type;
INSERT INTO personal_identity_type (pi_type,pi_category_type) VALUES ('AADHAR','CIVIL');
INSERT INTO personal_identity_type (pi_type,pi_category_type) VALUES ('PAN','CIVIL');
INSERT INTO personal_identity_type (pi_type,pi_category_type) VALUES ('PAN','PROFESSIONAL');
INSERT INTO personal_identity_type (pi_type,pi_category_type) VALUES ('DRIVING LICENSE','CIVIL');
INSERT INTO personal_identity_type (pi_type,pi_category_type) VALUES ('DRIVING LICENSE','PROFESSIONAL');
INSERT INTO personal_identity_type (pi_type,pi_category_type) VALUES ('VOTER ID','CIVIL');
INSERT INTO personal_identity_type (pi_type,pi_category_type) VALUES ('PASSPORT','CIVIL');
INSERT INTO personal_identity_type (pi_type,pi_category_type) VALUES ('PASSPORT','PROFESSIONAL');
INSERT INTO personal_identity_type (pi_type,pi_category_type) VALUES ('NSR','PROFESSIONAL');
INSERT INTO personal_identity_type (pi_type,pi_category_type) VALUES ('BIRTH','CIVIL');

DROP SEQUENCE SEQ_PI_DOCS;
CREATE SEQUENCE seq_pi_docs MINVALUE 100000 MAXVALUE 999999 START WITH 100000 INCREMENT BY 1 CACHE 100;

--ALTER TABLE PERSONAL_IDENTITY_DOCS DROP COLUMN v_lcnse_classes;

DROP TABLE PERSONAL_IDENTITY_DOCS;
CREATE TABLE personal_identity_docs (
    seq_pi_docs            VARCHAR(10) PRIMARY KEY,
    user_name              VARCHAR(45) NOT NULL,
    mobile_number          VARCHAR(15) NOT NULL,
    active_status          CHAR(1) DEFAULT 'Y',
    pan_id                 VARCHAR(20),
    aadhar_id              VARCHAR(20),
    passport_id            VARCHAR(20),
    dl_id                  VARCHAR(20),
    nsr_id                 VARCHAR(20),
    voter_id               VARCHAR(20),
    v_reg_number           VARCHAR(15),
    v_class                varchar(30),
    v_class_desc           varchar(100),
    pi_doc_type            VARCHAR(15) NOT NULL,
    pi_doc_ctgry_type      VARCHAR(12) NOT NULL,
    pi_primary_mob_num     VARCHAR(15) NOT NULL,
    pi_alternate_mob_num   VARCHAR(15) DEFAULT 'NA',
    doc_holder_name        VARCHAR(50) NOT NULL,
    pi_prnt_spse_grdn      VARCHAR(150) DEFAULT 'NA',
    blood_grp              VARCHAR(5),
    pi_date_of_birth       DATE NOT NULL,
    pi_address             VARCHAR(255) NOT NULL,
    pi_addr_city           VARCHAR(15) NOT NULL,
    pi_addr_state          VARCHAR(30) NOT NULL,
    pi_addr_pincode        VARCHAR(6) NOT NULL,
    v_lcnse_classes        VARCHAR(2), 
    first_issue_date       TIMESTAMP(6),
    re_issue_date          TIMESTAMP(6),
    reissue_indicator      CHAR(1) DEFAULT 'N',
    tenure_number          SMALLINT DEFAULT 01,
    expiry_date            TIMESTAMP(6),
    created_datetime       TIMESTAMP(6) DEFAULT systimestamp,
    modified_datetime      TIMESTAMP(6) DEFAULT systimestamp,
    FOREIGN KEY ( user_name,
                  mobile_number )
        REFERENCES USER_CREDENTIALS ( user_name,
                                  mobile_number )
            ON DELETE CASCADE,
    FOREIGN KEY ( v_reg_number )
        REFERENCES vehicle_details ( v_registration_num )
            ON DELETE CASCADE
);

DROP TABLE QR_BARCODE;
CREATE TABLE qr_barcode (
    qr_barcode      VARCHAR(30) PRIMARY KEY,
    product_owner   VARCHAR(45) NOT NULL,
    po_mobile       VARCHAR(15) NOT NULL,
    active_status   CHAR(1) DEFAULT 'Y',
    FOREIGN KEY ( product_owner,
                  po_mobile )
        REFERENCES user_CREDENTIALS ( user_name,
                                  mobile_number )
            ON DELETE CASCADE
);
DROP SEQUENCE SEQ_PRFT_LOSS;
CREATE SEQUENCE seq_prft_loss MINVALUE 100000 MAXVALUE 999999 START WITH 100000 INCREMENT BY 1 CACHE 100;

DROP TABLE PROFIT_LOSS;
CREATE TABLE profiT_loss (
    seq_prft_loss      INTEGER PRIMARY KEY,
    v_reg_number       VARCHAR(10),
    qr_barcode         VARCHAR(30),
    cost_price         VARCHAR(12) NOT NULL,
    selling_price      VARCHAR(12) NOT NULL,
    seller_name        VARCHAR(45) DEFAULT 'NA',
    seller_comm_perc   DECIMAL(4,2) DEFAULT 00.00,
    prft_lss_perc      DECIMAL(4,2) DEFAULT 00.00,
    FOREIGN KEY ( v_reg_number )
        REFERENCES vehicle_details ( v_registration_num )
            ON DELETE CASCADE,
    FOREIGN KEY ( qr_barcode )
        REFERENCES qr_barcode ( qr_barcode )
            ON DELETE CASCADE
);

DROP TABLE VEHICLE_DOC_TYPE;
CREATE TABLE VEHICLE_DOC_TYPE
(
    vdoc_type       VARCHAR(20) NOT NULL,
    active_status   char(1) DEFAULT 'Y'
);

TRUNCATE TABLE VEHICLE_DOC_TYPE;
INSERT INTO VEHICLE_DOC_TYPE (vdoc_type ) VALUES ('DRIVING LICENSE' );
INSERT INTO VEHICLE_DOC_TYPE (vdoc_type ) VALUES ('INSURANCE' );
INSERT INTO VEHICLE_DOC_TYPE (vdoc_type ) VALUES ('POLLUTION CONTROL' );
INSERT INTO VEHICLE_DOC_TYPE (vdoc_type ) VALUES ('REGISTRATION' );

DROP SEQUENCE SEQ_VDOC_ID;
CREATE SEQUENCE SEQ_VDOC_ID MINVALUE 100000 MAXVALUE 999999 START WITH 100000 INCREMENT BY 1 CACHE 100;


DROP TABLE VCERTIFICATE_REGISTRATION;
CREATE TABLE VCERTIFICATE_REGISTRATION (
    VEH_RC_ID VARCHAR(25) PRIMARY KEY,
    ACTIVE_STATUS CHARACTER(1) DEFAULT 'Y',
    VEHICLE_CLASS VARCHAR(100) NOT NULL,
    MAKER_CLASS VARCHAR(100) NOT NULL,
    BODY_TYPE VARCHAR(25) NOT NULL,
    V_MANUFACTURING_DATE DATE NOT NULL,
    CHASSIS_NUMBER VARCHAR(25) NOT NULL,
    ENGINE_NUMBER VARCHAR(30) NOT NULL,
    CUBIC_CAPACITY INTEGER NOT NULL,
    WHEEL_BASE INTEGER NOT NULL,
    SEATING_CAPACITY INTEGER NOT NULL,
    UNLADEN_WEIGHT INTEGER NOT NULL,
    COLOR VARCHAR(10) NOT NULL,
    VEHICLE_TAX INTEGER NOT NULL,
    TAX_TYPE VARCHAR(8) NOT NULL,
    CREATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    MODIFIED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

DROP TABLE VPOLLUTION_CONTROL_CERTIFICATE;
CREATE TABLE VPOLLUTION_CONTROL_CERTIFICATE (
    VEH_POL_CTRL VARCHAR(15) PRIMARY KEY,
    ACTIVE_STATUS CHARACTER(1) DEFAULT 'Y',
    CATALYST VARCHAR(3),
    ENGINE_TYPE VARCHAR(10) NOT NULL,
    VEHICLE_MAKE VARCHAR(30) NOT NULL,
    VEHICLE_MODEL VARCHAR(50) NOT NULL,
    CREATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
	MODIFIED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);


DROP TABLE VEHICLE_DOCS;
CREATE TABLE VEHICLE_DOCS (
    SEQ_VDOC_ID VARCHAR(10) PRIMARY KEY,
    VEH_RC_ID VARCHAR(15),
    VEH_POL_CTRL VARCHAR(15),
    VEH_DL_ID VARCHAR(15),
    VEHICLE_REG_NUM VARCHAR(10) NOT NULL,
    DOC_TYPE VARCHAR(20) NOT NULL,
    ACTIVE_STATUS CHARACTER(1) DEFAULT 'Y',
    DOC_REFERENCE_NUMBER VARCHAR(35) NOT NULL,
    DOC_HOLDER_NAME VARCHAR(50) NOT NULL,
    DOC_AUTHORITY VARCHAR(200) NOT NULL,
    AUTHORIZING_UNION VARCHAR(300) NOT NULL,
    VEHICLE_TYPE VARCHAR(15),
    FUEL_TYPE VARCHAR(10) NOT NULL,
    REGISTRATION_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    CREATED_DATETIME TIMESTAMP(6) DEFAULT  SYSTIMESTAMP,
    MODIFIED_DATETIME TIMESTAMP(6) DEFAULT  SYSTIMESTAMP,
    FOREIGN KEY (VEHICLE_REG_NUM) REFERENCES  VEHICLE_DETAILS(V_REGISTRATION_NUM) ON DELETE CASCADE,
    CONSTRAINT FK_V_RC FOREIGN KEY (VEH_RC_ID) REFERENCES VCERTIFICATE_REGISTRATION(VEH_RC_ID),
    CONSTRAINT FK_V_PCTRL FOREIGN KEY (VEH_POL_CTRL) REFERENCES VPOLLUTION_CONTROL_CERTIFICATE(VEH_POL_CTRL)
);


DROP TABLE BANK_AC_NUM_DETAILS;
CREATE TABLE BANK_AC_NUM_DETAILS (
AC_NUMBER VARCHAR(75) PRIMARY KEY,
ACTIVE_STATUS CHARACTER(1) DEFAULT 'Y',
CREATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
MODIFIED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

DROP TABLE ELECTRONIC_CARD_NUM_DETAILS;
CREATE TABLE ELECTRONIC_CARD_NUM_DETAILS(
CARD_NUMBER VARCHAR(25) PRIMARY KEY,
ACTIVE_STATUS CHARACTER(1) DEFAULT 'Y',
CREATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
MODIFIED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);


DROP TABLE BANK_ACC_CATEGORY;
CREATE TABLE BANK_ACC_CATEGORY(
    BANK_ACC_CTGRY VARCHAR(30) NOT NULL,
    BANK_ACC_TYPE VARCHAR(30) NOT NULL
);

TRUNCATE TABLE BANK_ACC_CATEGORY;
INSERT INTO BANK_ACC_CATEGORY VALUES ('SINGLE','CURRENT');
INSERT INTO BANK_ACC_CATEGORY VALUES ('SINGLE','SAVINGS');
INSERT INTO BANK_ACC_CATEGORY VALUES ('SINGLE','FIXED DEPOSIT');
INSERT INTO BANK_ACC_CATEGORY VALUES ('JOINT','CURRENT');
INSERT INTO BANK_ACC_CATEGORY VALUES ('JOINT','SAVINGS');
INSERT INTO BANK_ACC_CATEGORY VALUES ('JOINT','FIXED DEPOSIT');

DROP TABLE bank_account_details;
CREATE TABLE BANK_ACCOUNT_DETAILS (
	SEQ_BANK_ACC VARCHAR(10) PRIMARY KEY,
    USER_NAME VARCHAR(45) NOT NULL,
    MOBILE_NUMBER VARCHAR(15) NOT NULL,
    ACTIVE_STATUS CHAR(1) DEFAULT 'Y',
    ACCOUNT_NUMBER VARCHAR(75) NOT NULL,
    ELECTRONIC_CARD_NUM VARCHAR(25),
    ACC_HOLDER_NAME VARCHAR(70) NOT NULL,
    BANK VARCHAR(150) NOT NULL,
    BRANCH VARCHAR(100) NOT NULL,
    IFSC_CODE VARCHAR(15) NOT NULL,
    ACCOUNT_CATEGORY VARCHAR(12) DEFAULT 'SINGLE', -- JOINT
    ACCOUNT_TYPE VARCHAR(20) DEFAULT 'CURRENT', -- SAVINGS
    REGTD_MOBILE_NUM VARCHAR(15) NOT NULL,
    ALTRN_MOBILE_NUM VARCHAR(15) DEFAULT 'NO INFO',
    BALANCE VARCHAR(12) DEFAULT 'INR 0.00',
    CREATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
	MODIFIED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (ACCOUNT_NUMBER) 
        REFERENCES BANK_AC_NUM_DETAILS (AC_NUMBER) ON DELETE CASCADE,
	FOREIGN KEY (ELECTRONIC_CARD_NUM)
		REFERENCES ELECTRONIC_CARD_NUM_DETAILS (CARD_NUMBER),  
    FOREIGN KEY (USER_NAME, MOBILE_NUMBER) 
        REFERENCES USER_CREDENTIALS (USER_NAME, MOBILE_NUMBER) 
    ON DELETE CASCADE
);

DROP TABLE CARD_TYPES;
CREATE TABLE CARD_TYPES(
CARD_TYPE VARCHAR(20) NOT NULL);

TRUNCATE TABLE CARD_TYPES;
INSERT INTO CARD_TYPES VALUES ('CREDIT');
INSERT INTO CARD_TYPES VALUES ('DEBIT');
INSERT INTO CARD_TYPES VALUES ('EMI');
INSERT INTO CARD_TYPES VALUES ('MEDICAL');
INSERT INTO CARD_TYPES VALUES ('SHOPPING');
INSERT INTO CARD_TYPES VALUES ('TRANSPORTATION');

DROP SEQUENCE SEQ_ELEC_CRDS;
CREATE SEQUENCE SEQ_ELEC_CRDS MINVALUE 100000 MAXVALUE 999999 START WITH 100000 INCREMENT BY 1 CACHE 100;

DROP TABLE ELECTRONIC_CARDS;
CREATE TABLE ELECTRONIC_CARDS (
	SEQ_ELEC_CRDS VARCHAR(10) PRIMARY KEY,
    USER_NAME VARCHAR(40) NOT NULL,
    MOBILE_NUMBER VARCHAR(15) NOT NULL,
    CARD_NUMBER VARCHAR(25) NOT NULL,
    CARD_CATEGORY CHAR(1) NOT NULL,
    BANK_ACNT_NUMBER VARCHAR(75),
    ACTIVE_STATUS CHAR(1) DEFAULT 'Y',
    CARDHOLDER_NAME VARCHAR(25) NOT NULL,
    CARD_PROVIDER VARCHAR(150) NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
    CREDIT_LIMIT VARCHAR(10) DEFAULT 'INR 0.0',
    POINTS_AVAILABLE VARCHAR(5) DEFAULT '0',
    CREATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
	MODIFIED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CRD_DBT_UC FOREIGN KEY  (USER_NAME, MOBILE_NUMBER)
       REFERENCES USER_CREDENTIALS (USER_NAME, MOBILE_NUMBER) 
	ON DELETE CASCADE,
    CONSTRAINT FK_CRD_DBT_BA FOREIGN KEY (BANK_ACNT_NUMBER)
     REFERENCES BANK_AC_NUM_DETAILS (AC_NUMBER) ON DELETE CASCADE,
	CONSTRAINT FK_EC_NUM FOREIGN KEY  (CARD_NUMBER) REFERENCES ELECTRONIC_CARD_NUM_DETAILS (CARD_NUMBER) ON DELETE CASCADE
);

DROP SEQUENCE SEQ_EMI_ID;
CREATE SEQUENCE SEQ_EMI_ID MINVALUE 100000 MAXVALUE 999999 START WITH 100000 INCREMENT BY 1 CACHE 100;

DROP TABLE EMI_DETAILS;
CREATE TABLE  EMI_DETAILS (
	SEQ_EMI_ID VARCHAR(10) PRIMARY KEY,
    PRODUCT_ID VARCHAR(30),
	VEHICLE_REG_NUMBER VARCHAR(10),
    ECARD_NUM VARCHAR(25),
	BANK_ACC_NUM VARCHAR(75),
    ACTIVE_STATUS CHAR(1) DEFAULT 'Y',
	PRODUCT_PRICE VARCHAR(12) NOT NULL,
    EMI_PROVIDER VARCHAR(80) NOT NULL,
    EMI_START_DATE DATE NOT NULL,
    EMI_INTEREST_RATE VARCHAR(6) DEFAULT '0.00',
    EMI_AMOUNT VARCHAR(10) DEFAULT '0.00',
    EMI_INSTL_COUNT VARCHAR(2) DEFAULT '1',
    CREATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
	MODIFIED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_EMI_V FOREIGN KEY (PRODUCT_ID) 
			REFERENCES QR_BARCODE(QR_BARCODE) ON DELETE CASCADE,
    CONSTRAINT FK_EMI_VH_REG  FOREIGN KEY  (VEHICLE_REG_NUMBER) REFERENCES VEHICLE_DETAILS(V_REGISTRATION_NUM)
			ON DELETE CASCADE,
	CONSTRAINT FK_EMI_EC FOREIGN KEY (ECARD_NUM) REFERENCES ELECTRONIC_CARD_NUM_DETAILS (CARD_NUMBER),
    CONSTRAINT FK_EMI_BAN FOREIGN KEY(BANK_ACC_NUM) REFERENCES BANK_AC_NUM_DETAILS(AC_NUMBER)
); 


DROP TABLE EDUCATION_STANDARD;
CREATE TABLE EDUCATION_STANDARD(
EDU_STANDRD VARCHAR(40),
EDU_DGREE VARCHAR(25),
COURSE VARCHAR(200),
COURSE_ALIAS VARCHAR(10)
);

TRUNCATE TABLE EDUCATION_STANDARD;
INSERT INTO EDUCATION_STANDARD VALUES ('HIGH SCHOOL','GRADE 10','STATE BOARD','SB');
INSERT INTO EDUCATION_STANDARD VALUES ('HIGH SCHOOL','GRADE 10','CENTRAL BOARD','CBSE');
INSERT INTO EDUCATION_STANDARD VALUES ('SECONDARY HIGH SCHOOL', 'INTERMEDIATE','MATHEMATICS, PHYSICS AND CHEMISTRY', 'M.P.C');
INSERT INTO EDUCATION_STANDARD VALUES ('SECONDARY HIGH SCHOOL','INTERMEDIATE','MATHEMATICS, ECONOMICS AND COMMERCE','M.E.C');
INSERT INTO EDUCATION_STANDARD VALUES ('SECONDARY HIGH SCHOOL','INTERMEDIATE','CIVICS, ECONOMICS AND COMMERCE','C.E.C');
INSERT INTO EDUCATION_STANDARD VALUES ('SECONDARY HIGH SCHOOL','INTERMEDIATE','HISTORY, ECONOMICS AND COMMERCE','H.E.C');
INSERT INTO EDUCATION_STANDARD VALUES ('SECONDARY HIGH SCHOOL','INTERMEDIATE','BIOLOGY, PHYSICS AND CHEMISTRY','BI.P.C');
INSERT INTO EDUCATION_STANDARD VALUES ('SECONDARY HIGH SCHOOL','OTHERS',NULL,NULL);
INSERT INTO EDUCATION_STANDARD VALUES ('GRADUATION','BACHELOR OF TECHNOLOGY','ELECTRICAL AND ELECTRONICS','EE');
INSERT INTO EDUCATION_STANDARD VALUES ('GRADUATION','BACHELOR OF TECHNOLOGY','ELECTRONICS AND COMMUNICATION','EC');
INSERT INTO EDUCATION_STANDARD VALUES ('GRADUATION','BACHELOR OF TECHNOLOGY','MECHANICAL','M');
INSERT INTO EDUCATION_STANDARD VALUES ('GRADUATION','BACHELOR OF TECHNOLOGY','INFORMATION TECHNOLOGY','IT');
INSERT INTO EDUCATION_STANDARD VALUES ('GRADUATION','BACHELOR OF TECHNOLOGY','COMPUTER SCIENCES','CS');
INSERT INTO EDUCATION_STANDARD VALUES ('GRADUATION','BACHELOR OF TECHNOLOGY','ROBOTICS AND AUTOMATION','RA');
INSERT INTO EDUCATION_STANDARD VALUES ('GRADUATION','BACHELOR OF TECHNOLOGY','AUTOMOBILE','AT');
INSERT INTO EDUCATION_STANDARD VALUES ('GRADUATION','BACHELOR OF TECHNOLOGY','AEROSPACE','AS');
INSERT INTO EDUCATION_STANDARD VALUES ('GRADUATION','BACHELOR OF TECHNOLOGY','CHEMICAL AND METALLURGICAL','CM');
INSERT INTO EDUCATION_STANDARD VALUES ('POST-GRADUATION','MASTER OF TECHNOLOGY','ELECTRICAL AND ELECTRONICS','EE');
INSERT INTO EDUCATION_STANDARD VALUES ('POST-GRADUATION','MASTER OF TECHNOLOGY','ELECTRONICS AND COMMUNICATION','EC');
INSERT INTO EDUCATION_STANDARD VALUES ('POST-GRADUATION','MASTER OF TECHNOLOGY','MECHANICAL','M');
INSERT INTO EDUCATION_STANDARD VALUES ('POST-GRADUATION','MASTER OF TECHNOLOGY','INFORMATION TECHNOLOGY','IT');
INSERT INTO EDUCATION_STANDARD VALUES ('POST-GRADUATION','MASTER OF TECHNOLOGY','COMPUTER SCIENCES','CS');
INSERT INTO EDUCATION_STANDARD VALUES ('POST-GRADUATION','MASTER OF TECHNOLOGY','ROBOTICS AND AUTOMATION','RA');
INSERT INTO EDUCATION_STANDARD VALUES ('POST-GRADUATION','MASTER OF TECHNOLOGY','AUTOMOBILE','AT');
INSERT INTO EDUCATION_STANDARD VALUES ('POST-GRADUATION','MASTER OF TECHNOLOGY','AEROSPACE','AE');
INSERT INTO EDUCATION_STANDARD VALUES ('POST-GRADUATION','MASTER OF TECHNOLOGY','CHEMICAL AND METALLURGICAL','CM');
INSERT INTO EDUCATION_STANDARD VALUES ('POST-GRADUATION','OTHERS',NULL,NULL);


DROP SEQUENCE SEQ_EDU_DOC_ID;
CREATE SEQUENCE SEQ_EDU_DOC_ID MINVALUE 100000 MAXVALUE 999999 START WITH 100000 INCREMENT BY 1 CACHE 100;

DROP TABLE EDUCATION_DOCS;
CREATE TABLE EDUCATION_DOCS (    
    SEQ_EDU_DOC_ID VARCHAR(10) PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL,
    MOBILE_NUMBER VARCHAR(15) NOT NULL,
    DOC_REF_NUM VARCHAR(25) NOT NULL,
    EDU_STANDARD VARCHAR(40) NOT NULL,
    CANDIDATE_ROLL_NUM VARCHAR(20) NOT NULL,
    CANDIDATE_NAME VARCHAR(40) NOT NULL,
    EDU_DEGREE VARCHAR(10) NOT NULL,
    SPECIALIZATION VARCHAR(200) NOT NULL,
    SEMESTER_YEAR VARCHAR(2) DEFAULT 'NA',
    NAME_OF_INSTITUTE VARCHAR(255) NOT NULL,
    INSTITUTE_GOVERNING_BODY VARCHAR(200) NOT NULL,
    AFFILIATED_TO_UNIVERSITY VARCHAR(255) DEFAULT 'NA',
    TOTAL_MARKS VARCHAR(5) NOT NULL,
    MAXIMUM_MARKS VARCHAR(5) NOT NULL,
    PERCENTAGE_CGPA_TYPE VARCHAR(10) DEFAULT 'PERCENTAGE',
    PERCENTAGE_CGPA_VALUE VARCHAR(8) NOT NULL,
    MONTH_YEAR_PASSING VARCHAR(5) NOT NULL,
    PASSOUT_BATCH VARCHAR(5) NOT NULL,
    DOC_ISSUE_DATE DATE NOT NULL,
    CREATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP(6),
    MODIFIED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP(6),
    CONSTRAINT FK_ED_UC FOREIGN KEY (USER_NAME, MOBILE_NUMBER)
        REFERENCES USER_CREDENTIALS (USER_NAME, MOBILE_NUMBER)
        ON DELETE CASCADE
);

DROP SEQUENCE SEQ_PRODUCT;
CREATE SEQUENCE SEQ_PRODUCT MINVALUE 100000 MAXVALUE 999999 START WITH 100000 INCREMENT BY 1 CACHE 100;

DROP TABLE PRODUCT_DETAILS;
CREATE TABLE PRODUCT_DETAILS (
	SEQ_PRODUCT VARCHAR(10) PRIMARY KEY,
	PRODUCT_ID VARCHAR(30),
    V_REGISTERED_NUMBER VARCHAR(18),
    BANK_AC_NUM VARCHAR(20),
    ELECTRONIC_CRD_NUM VARCHAR(20),
    WARRANTY_DOC_ID VARCHAR(20) DEFAULT 'NA',
    ACTIVE_STATUS CHAR(1) DEFAULT 'Y', -- WARRANTY_ACTIVE_STATUS
    IS_VEHICLE CHAR(1) DEFAULT 'N', -- 0 IF NOT A VEHICLE.
    WARRANTY_MODE VARCHAR(10) DEFAULT 'ON SITE',
    WARRANTY_HOLDER_NAME VARCHAR(45) NOT NULL,
    PRODUCT_NAME VARCHAR(80) NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(200) DEFAULT 'NO INFO',
    PURCHASE_MODE VARCHAR(15) NOT NULL, -- ONLINE , RETAIL, FROM INDIVIDUAL
    PRODUCT_STATE VARCHAR(15) DEFAULT 'NEW', -- ALSO CAN BE 'REFURBISHED'
    PRODUCT_PRICE VARCHAR(12) NOT NULL, 
    PRODUCT_MERCHANT VARCHAR(80),
    MERCHANT_TYPE VARCHAR(30) DEFAULT 'RETAILER', -- RETAILER/ONLINE SELLER/INDIVIDUAL
    MERCHANT_CONTACT VARCHAR(15),
    MERCHANT_EMAIL VARCHAR(50) DEFAULT 'NO INFO',
    PURCHASE_DATE DATE NOT NULL,
    WARRANTY_EXP_DATE DATE NOT NULL,
    CREATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
	MODIFIED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PRDET_QRBR FOREIGN KEY (PRODUCT_ID)
        REFERENCES QR_BARCODE (QR_BARCODE) ON DELETE CASCADE,
	CONSTRAINT FK_PRDET_VDET FOREIGN KEY  (V_REGISTERED_NUMBER) 
        REFERENCES VEHICLE_DETAILS (V_REGISTRATION_NUM) ON DELETE CASCADE,
    CONSTRAINT FK_PRDET_BAC_NUM FOREIGN KEY  (BANK_AC_NUM) 
		REFERENCES BANK_AC_NUM_DETAILS (AC_NUMBER),
    CONSTRAINT FK_PRDET_ECARD_NUM FOREIGN KEY  (ELECTRONIC_CRD_NUM) 
		REFERENCES ELECTRONIC_CARD_NUM_DETAILS (CARD_NUMBER)
);
